###
POST  http://localhost:5100/question
Content-Type: application/json

{
    "user_id":"17f732d4-ef68-4e79-aa43-16e69fc060e1",
    "question":"How is programming/",
    "date":"2020-2-15"
}
###
GET  http://localhost:5100/question

###
GET  http://localhost:5100/question/user/11fb2695-955d-435b-90ce-58551bd438ad

###
GET  http://localhost:5100/question/a218ebf5-818c-4539-9ab8-6cd19917dfa2

###
DELETE http://localhost:5100/question/a96f0ff0-8be7-4d34-b7a5-251180040418
Content-Type: application/json

{
    "question_id":"377f0421-8456-48f0-a38f-01f1767abb44",
    "user_id":"11fb2695-955d-435b-90ce-58551bd43a8ad"
}


###
POST  http://localhost:5100/answers
Content-Type: application/json

{
    "questionid":"377f0421-8456-48f0-a38f-01f1767abb44",
    "uid":"11fb2695-955d-435b-90ce-58551bd438ad",
    "answer":"You can use the array reversereverese method" 
}

###
GET  http://localhost:5100/answers/377f0421-8456-48f0-a38f-01f1767abb44,17f732d4-ef68-4e79-aa43-16e69fc060e1
Content-Type: application/json


###
POST http://localhost:5100/comment
Content-Type: application/json

{
    "answer_id":"e6f1f5e9-5086-4316-9922-a857df1c6b6f",
    "user_id":"11fb2695-955d-435b-90ce-58551bd438ad",
    "comment":"This solution does not work"
}   

###
GET  http://localhost:5100/comment/e6f1f5e9-5086-4316-9922-a857df1c6b6f



###
POST http://localhost:5100/votes
Content-Type: application/json

{
    "answer_id":"e6f1f5e9-5086-4316-9922-a857df1c6b6f",
    "user_id":"17f732d4-ef68-4e79-aa43-16e69fc060e1",
    "like":1,   
    "dislike":0
}   



###
GET  http://localhost:5100/question/search
Content-Type: application/json

###
POST  http://localhost:5100/question/mostanswered
Content-Type: application/json

{
    "range":2
}